version: '3'
services:

  # PHP Service
  app:
    build:
      args:
        user: maulana
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sistem-penjualan-app
    container_name: sistem-penjualan-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sistem-penjualan-network

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: sistem-penjualan-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - sistem-penjualan-network

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: sistem-penjualan-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - sistem-penjualan-network

  # Redis Service (for Caching)
  redis:
    image: redis:alpine
    container_name: sistem-penjualan-redis
    restart: unless-stopped
    networks:
      - sistem-penjualan-network

networks:
  sistem-penjualan-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
